### ISSUE TITLE
Bash script does not work on macos, likely not on linux either

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS-Incubator/registry#40]
** Short description **
The script registry-manager does not launch on macos. it has errors.
I had to correct 2 things so that is works:
- replace "dev/nul" with "/dev/null"
- add export before the assignement of variable REGISTRY_MANAGER_HOME

See attached updated script.

1. registry-manager create-registry
2. See error

**Expected behavior**
The script should work

** Version of Software Used**
3.2.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS but I am wondering if this could work on linux

**Additional context**

**Comment by tdddblog** [comment]
On CentOS 8 it works as is. Without any changes.

**Comment by tdddblog** [comment]
The script doesn't work if /dist folder has registry-manager-x.y.z-apidocs.jar. Apicdocs jar appeared in version 3.x. It was not there in version 2.x.

**Comment by jordanpadams** [comment]
@tdddblog this does not fix the issues with the javadocs.jar. i understand the concern that the javadocs are not necessary, but they are going to continue to be produced because it is apart of the build automation

**Comment by jordanpadams** [comment]
@tdddblog I see what happened. the update was in the ZIP assembly but not the tar.gz.

**Comment by jordanpadams** [comment]
updated per ac44e80f6

**Comment by tloubrieu-jpl** [comment]
The zip package version 3.2.2 still has the javadoc jar. This does not block the release for the build.
